/* Generated by wayland-scanner 1.23.1 */

#ifndef EXT_FOREIGN_TOPLEVEL_LIST_V1_ENUM_PROTOCOL_H
#define EXT_FOREIGN_TOPLEVEL_LIST_V1_ENUM_PROTOCOL_H

#ifdef  __cplusplus
extern "C" {
#endif

#ifdef  __cplusplus
}
#endif

#endif
