/* Generated by wayland-scanner 1.23.1 */

#ifndef SINGLE_PIXEL_BUFFER_V1_ENUM_PROTOCOL_H
#define SINGLE_PIXEL_BUFFER_V1_ENUM_PROTOCOL_H

#ifdef  __cplusplus
extern "C" {
#endif

#ifdef  __cplusplus
}
#endif

#endif
